version: "3"

volumes:
  static:
  sqlite:

services:
  redis:
    image: redis:latest
    expose:
      - "6379"
  web:
    build:
      context: ./docker/web/
    expose:
      - "8000"
    env_file:
      - .env
    working_dir: /usr/src/web
    volumes:
      - ./web:/usr/src/web
      - static:/usr/src/web/public/static
      - sqlite:/usr/src/web/sqlite
    links:
      - redis:redis
    depends_on:
      - redis
    command: ./run.sh
  nginx:
    domainname: localhost
    # restart: always
    build:
      context: ./docker/nginx/
    ports:
      - "8181:8181"
    volumes:
      - ./web/public:/var/www:ro
      - static:/var/www/static:ro
    links:
      - web:web
    depends_on:
      - web
