version: "3"

volumes:
  static:
  sqlite:

networks:
  net:
    driver: bridge

services:
  redis:
    image: redis:latest
    networks:
      - net
    expose:
      - "6379"
  web:
    build:
      context: ./docker/web/
    expose:
      - "8000"
    env_file:
      - .env
    working_dir: /usr/src/web
    volumes:
      - ./web:/usr/src/web
      - static:/usr/src/web/public/static
      - sqlite:/usr/src/web/sqlite
    networks:
      - net
    depends_on:
      - redis
    command: ./run.sh
  nginx:
    domainname: "pols.local"
    # restart: always
    build:
      context: ./docker/nginx/
    ports:
      - "8001:80"
    volumes:
      - ./web/public:/var/www:ro
      - static:/var/www/static:ro
    networks:
      - net
    depends_on:
      - web
